server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Blog?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
    username: root
    password: '#252012'
    driver-class-name: com.mysql.cj.jdbc.Driver
#    连接池配置
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false

  devtools:
      restart:
        # 开启热部署（更改文件后，自动重启）
        enabled: true
        ## 设置哪些资源变动后不触发热部署，会覆盖默认的exclude内容（资源不会触发重启，但会触发实时重新加载）
        # exclude: WEB-INF/**,static/**
        ## 监控额外的路径（优先于exclude）
        # additional-paths: src/main/java
  redis:
    host: 192.168.2.129
    port: 6379
    username: default
    password: 'linux02'
    database: 1
#    默认使用lettuce
    lettuce:
      pool:
#        最大连接数，最大空闲数，最小空闲数
        max-active: 5
        max-idle: 5
        min-idle: 0
  cache:
#    使用redis缓存
    type: redis


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
#      logic-delete-field: isDelete
      logic-delete-value: 0
      logic-not-delete-value: 1

knife4j:
  enable: true
  openapi:
    title: Serein博客API接口测试
    description: "Swagger API接口测试"
    version: v1.0
    group:
      swagger-api:
        api-rule-resources:
          - com.serein.controller

#自定义变量
custom:
  salt: 'serein'
  token: 'SEREINSMILE'