server:
  port: 8081
  servlet:
    context-path: /api

spring:
  mail:
    username: wwqqblog@qq.com
    password: ckrhpfvavfeuciej
    host: smtp.qq.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  datasource:
    url: jdbc:mysql://localhost:3306/Blog?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
    username: root
    password: '#252012'
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 6
      minimum-idle: 3
      jdbc-url: jdbc:mysql://localhost:3306/Blog?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
      username: root
      password: '#252012'
      driver-class-name: com.mysql.cj.jdbc.Driver
  #    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      min-idle: 3
#      max-active: 6
#      max-wait: 60000
#      initial-size: 3
##      druid的web监控
#      stat-view-servlet:
#        enabled: true                   # 启用StatViewServlet
#        url-pattern: /druid/* # 访问内置监控页面的路径，内置监控页面的首页是/druid/index.html
#        reset-enable: false              # 不允许清空统计数据,重新计算
#        login-username: root # 配置监控页面访问密码
#        login-password: 123
#        allow: 127.0.0.1 # 允许访问的地址，如果allow没有配置或者为空，则允许所有访问
  redis:
    host: 192.168.2.129
    port: 6379
    username: default
    password: 'linux02'
    database: 1
#    默认使用lettuce
    lettuce:
      pool:
#        最大连接数，最大空闲数，最小空闲数
        max-active: 10
        max-idle: 5
        min-idle: 3
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB



#  cache:
#    使用redis缓存
#    type: redis

#  elasticsearch:
#    uris: 'localhost:9200'

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
#      logic-delete-field: isDelete
      logic-delete-value: 0
      logic-not-delete-value: 1

logging:
  level:
    com:
      serein:
        mapper: info
        service: info
        controller: info

knife4j:
  enable: true
  openapi:
    title: 'Serein博客API接口测试'
    version: v1.0
    description: '无问青秋博客'
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.serein.controller


#自定义变量
custom:
  salt: 'serein'
#  添加用户的初始密码
  originPassword: '123456'

oss:
  accessKey: ''
  secretKey: ''
  endPoint: ''
  bucket: ''
#jwt配置
#jwt:
#  token:
#    tokenExpiration: 30 #有效时间,单位分钟
#    tokenSignKey: 'tokenSignKey'

#java -jar worker-0.0.4-SNAPSHOT.jar --etcd.server=127.0.0.1:2379
hotkey:
  push-period: 60
  app-name: blog
  etcd-server: http://localhost:2379
#  hoeKey默认存在本地缓存，这里我就存在redis
  caffeine-size: 1000
