server:
  port: 8081
  servlet:
    context-path: /api
spring:
  ai:
    dashscope:
      api-key: xxx
      chat:
        options:
          model: qwen-plus
  mail:
    username:
    password:
    host: smtp.qq.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  datasource:
    url: jdbc:mysql://xxxx:3306/blog?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 6
      max-wait: 60000
      initial-size: 3
      #      druid的web监控
      stat-view-servlet:
        enabled: true                   # 启用StatViewServlet
        url-pattern: /druid/* # 访问内置监控页面的路径，内置监控页面的首页是/druid/index.html
        reset-enable: false              # 不允许清空统计数据,重新计算
        login-username: root # 配置监控页面访问密码
        login-password:
        allow:  # 允许访问的地址，如果allow没有配置或者为空，则允许所有访问
  cache:
    type: redis
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 6MB
  data:
    redis:
      username: default
      host:
      port: 6379
      password:
      database: 1
      jedis:
        pool:
          # 最大连接数，最大空闲数，最小空闲数
          max-active: 5
          max-idle: 2
          min-idle: 2
          enabled: true
      #    缓存10min，允许缓存null值防止缓存穿透

  #  elasticsearch:
  #    uris: 'localhost:9200'
  #easy-es:
  #  compatible: true # 兼容模式开关,默认为false,若您的es客户端版本小于8.x,务必设置为true才可正常使用,8.x及以上则可忽略此项配置
  #  enable: true # 默认为true,若为false时,则认为不启用本框架
  #  address: 127.0.0.0:9200
  # username:
  # password:

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #      logic-delete-field: isDelete
      logic-delete-value: 0
      logic-not-delete-value: 1

logging:
  level:
    com:
      serein:
        mapper: debug
        service: debug
        controller: debug

knife4j:
  enable: true
  openapi:
    title: 'Serein博客API接口测试'
    version: v1.0
    description: '无问青秋博客'
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.serein.controller



#自定义变量
custom:
  #  添加用户的初始密码
  originPassword: '123456user'

sa-token:
  token-name: authorization
  # token有效期，同一账号先后多端登录，token过期后先删除token-session，待该账号下所有token全部过期后才删除account-session。
  timeout: 7200
  is-log: true
  auto-renew: true