server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Blog?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
    username: root
    password: '#252012'
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      min-idle: 3
      max-active: 6
      max-wait: 60000
      initial-size: 3
  redis:
    host: 192.168.2.129
    port: 6379
    username: default
    password: 'linux02'
    database: 1
#    默认使用lettuce
    lettuce:
      pool:
#        最大连接数，最大空闲数，最小空闲数
        max-active: 5
        max-idle: 5
        min-idle: 0
#  cache:
#    使用redis缓存
#    type: redis

  elasticsearch:
    uris: 'localhost:9200'

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
#      logic-delete-field: isDelete
      logic-delete-value: 0
      logic-not-delete-value: 1

logging:
  level:
    com:
      serein:
        mapper: debug
        service: info
        controller: info

knife4j:
  enable: true
  openapi:
    title: 'Serein博客API接口测试'
    version: v1.0
    description: '无问青秋博客'
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.serein.controller


#自定义变量
custom:
  salt: 'serein'
#  添加用户的初始密码
  originPassword: '123456'

#jwt配置
#jwt:
#  token:
#    tokenExpiration: 10 #有效时间,单位分钟
#    tokenSignKey: 'SEREINSMILE'  #当前程序签名秘钥 自定义